%Troubleshoots discrepancies between standard form and Levi-Civita form
%integration. Requires a Levi-Civita context c and a corresponding 
%standard context c1, such as the context objects generated by running 
%[c,c1] = Sun_Jupiter_LCR_PCR3BP_Context()
%at the command window.

fixedRadiusAnalysis
eHandle(0,[examplepts;zeros(1,size(examplepts,2))])

close all;

figure; 
sollc = integ(timesexample,examplelc,c);
[~,pts] = lc2standard(sollc.x,sollc.y,mu);
cplot(pts,c);
hold on;
[~,~,solstandard]=integplot(exampletimesstandard,[endubdsorted(:,examplebd);0],...
                    c1,'+')
cplot(endubdsorted(:,examplebd),c,'o')
xlabel('$x$','Interpreter','Latex')
ylabel('$y$','Interpreter','Latex')
legend('Levi-Civita Trajectory','Standard Trajectory','Initial Condition')
set(gca,'FontSize',20)